mode_ci:
  enabled: true # default is false
  branch: 'master' # default is master
branch: 'master' # default is master
path: # Set path where report will be saved (tmp/rubycritic by default)
threshold_score: 10 # default is 0
deduplicate_symlinks: true # default is false
suppress_ratings: true # default is false
no_browser: true # default is false
formats: # Available values are: html, json, console, lint. Default value is html.
  - console
  - html
minimum_score: 81.9 # default is 0
paths: # Files to analyse.
